import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Project from "../components/Project";
import project from "../static/projects.json"

const Home = () => {
  const allProjects = project
  return (
    <>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="lg:pt-32 pl-32">
        <h1 className="text-4xl lg:text-4xl">Hello.</h1>
        <h1 className="text-4xl lg:text-5xl">I'm Abdulghani.</h1>

        <h1>Description about myself</h1>

        <h1 className="mt-12 mb-2">Quick Links</h1>

        <div className="flex">
          <div className="border-l-2 border-y-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            Skills
          </div>
          <div className="border-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            About
          </div>
          <div className="border-r-2 border-y-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            Contacts
          </div>
        </div>

        <h1 className="text-3xl mb-4 mt-48">Projects</h1>

        <div className="grid grid-cols-4 gap-y-8">
          {
            allProjects.map((item) => (
              <div>
                <Project key={item.id} projectTitle={item.title} projectDescription={item.description} />
              </div>
            ))
          }
        </div>

      </div>
    </>
  );
};

export default Home;
