import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-8 pl-8">
        <h1 className="text-3xl">Hello.</h1>
        <h1 className="text-3xl">I'm Abdulghani.</h1>

        <h1>Description about myself</h1>

        <h1 className="mt-48 mb-2">Quick Links</h1>

        <div className="flex">
          <div className="border-l-2 border-y-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            Projects
          </div>
          <div className="border-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            About
          </div>
          <div className="border-r-2 border-y-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            Contacts
          </div>
        </div>

        <h1 className="text-3xl mb-2 mt-48">Projects</h1>

        {/* Single project card */}
        <div className="relative">
          {/* Black Layer */}
          <div className="bg-black w-96 z-0 relative -right-2 top-2 h-32"></div>

          <div className="border-2 border-slate-900 w-96 z-10 absolute top-0 bg-white">
            <div className="border-b-2 border-slate-900">IMAGE</div>

            <div className="pl-2 py-2">
              <h1 className="">project title</h1>
              <p className="text-xs">project small description</p>

              <button className="px-2 py-0.5 mt-4 border-2 border-slate-900 bg-orange-300 text-sm hover:bg-orange-400 duration-200">
                View project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
