import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Project from "../components/Project";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-8 pl-8">
        <h1 className="text-3xl">Hello.</h1>
        <h1 className="text-3xl">I'm Abdulghani.</h1>

        <h1>Description about myself</h1>

        <h1 className="mt-48 mb-2">Quick Links</h1>

        <div className="flex">
          <div className="border-l-2 border-y-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            Projects
          </div>
          <div className="border-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            About
          </div>
          <div className="border-r-2 border-y-2 border-slate-900 p-1 px-4 bg-orange-300 cursor-pointer hover:bg-orange-400 duration-200">
            Contacts
          </div>
        </div>

        <h1 className="text-3xl mb-2 mt-48">Projects</h1>

        <Project imageUrl="image" projectTitle="search engine" projectDescription="search engine for rafraf.com" />

      </div>
    </div>
  );
};

export default Home;
